import { defineConfig } from "wxt";

// See https://wxt.dev/api/config.html
export default defineConfig({
  extensionApi: "chrome",
  modules: ["@wxt-dev/module-react"],
  srcDir: "src",
  entrypointsDir: "entrypoints",
  manifestVersion: 3,
  manifest: {
    name: "extension ownership monitor",
    browser_specific_settings: {
      gecko: {
        // randomly generated by AMO (beta listing)
        id: "756a9831-4a11-4f92-bd1a-16d00362e5ce"
      }
    },
    permissions: ["alarms", "management", "storage"],
    // TODO: use @wxt-dev/auto-icons to generate from single icon,
    //  so future logo changes are easier
    icons: {
      "16": "logo-16.png",
      "48": "logo-48.png",
      "128": "logo-128.png"
    },
    action: {
      "default_popup": "popup/index.html"
    },
    vite: () => ({
      css: {
        // ensures PostCSS processes the CSS
        postcss: "./postcss.config.js",
      },
    })
  },
});
